core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab_0.urls')),
    path('lab_1/', include('lab_1.urls')),
    path('lab_2/', include('lab_2.urls')),
    path('lab_3/', include('lab_3.urls')),
    path('lab_4/', include('lab_4.urls')),
    path('lab_5/', include('lab_5.urls')),
    path('lab_6/', include('lab_6.urls')),
    path('lab_7/', include('lab_7.urls')),
    path('lab_8/', include('lab_8.urls')),
    path('lab_9/', include('lab_9.urls')),
]

lab_0/urls.py
from django.urls import path
from . import views

app_name = 'lab_0'

urlpatterns = [
    path('', views.index, name='index'),
    path('ppw/', views.ppw, name='ppw')
]

lab_1/urls.py
from django.urls import path
from . import views

app_name = 'lab_1'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_2/urls.py
from django.urls import path
from . import views

app_name = 'lab_2'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_3/urls.py
from django.urls import path
from . import views

app_name = 'lab_3'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_4/urls.py
from django.urls import path
from . import views

app_name = 'lab_4'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_5/urls.py
from django.urls import path
from . import views

app_name = 'lab_5'

urlpatterns = [
    path('', views.index, name='index'),
    path('matkul/', views.matkul, name='matkul'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('delete/<int:pk>/', views.delete, name='delete')
]

lab_6/urls.py
from django.urls import path
from . import views

app_name = 'lab_6'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('kegiatan/<int:pk>/', views.matkul, name='kegiatan')
]

lab_7/urls.py
from django.urls import path
from . import views

app_name = 'lab_7'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_8/urls.py
from django.urls import path
from . import views

app_name = 'lab_8'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_9/urls.py
from django.urls import path
from . import views

app_name = 'lab_9'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

lab_0/models.py
from django.db import models

# Create your models here.

lab_1/models.py
from django.db import models

# Create your models here.

lab_5/forms.py
from django.forms import ModelForm
from . import models


class MatkulForm(ModelForm):
    class Meta:
        model = models.Matkul
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'semester', 'ruang']

lab_0/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req, 'lab_0/index.html', {'page_title': 'Home'})

def ppw(req):
    return render(req, 'lab_0/ppw.html', {'page_title': 'Tugas-tugas PPW'})

lab_1/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req, 'lab_1/index.html', {'page_title': 'Story 1'})

lab_2/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req, 'lab_2/index.html', {'page_title': 'Story 2'})

lab_3/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req, 'lab_3/index.html', {'page_title': 'Story 3'})

lab_4/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req, 'lab_4/index.html', {'page_title': 'Story 4'})

lab_5/views.py
from django.shortcuts import render, redirect
from . import forms, models

# Create your views here.


def index(req):
    if req.method == 'POST':
        form = forms.MatkulForm(req.POST)
        if form.is_valid():
            form.save()
            return redirect('/lab_5/matkul/')
    else:
        form = forms.MatkulForm()
        return render(req, 'lab_5/index.html', {'page_title': 'Story 5', 'form': form})


def matkul(req):
    all_matkul = models.Matkul.objects.all().values()
    return render(req, 'lab_5/matkul.html', {'page_title': 'Daftar Matkul', 'all_matkul': all_matkul})

def detail(req, pk): # pragma: no cover
    try:
        matkul = models.Matkul.objects.get(pk=pk)
        return render(req, 'lab_5/detail.html', {'page_title': 'Detail Matkul', 'matkul': matkul})
    except models.Matkul.DoesNotExist:
        return redirect('/lab_5/matkul/')

def delete(req, pk): # pragma: no cover
    try:
        matkul = models.Matkul.objects.get(pk=pk)
        matkul.delete()
        return redirect('/lab_5/matkul/')
    except models.Matkul.DoesNotExist:
        return redirect('/lab_5/matkul/')

lab_6/views.py
from django.shortcuts import render

# Create your views here.

lab_7/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req, 'lab_7/index.html', {'page_title': 'Story 7'})

lab_8/views.py
from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req, 'lab_8/index.html', {'page_title': 'Story 8'})

lab_9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.urls import reverse

# Create your views here.

def index(req):
    if req.user.is_authenticated:
        return render(req, 'lab_9/index.html', {'page_title': 'Private Page', 'username': req.user.username})
    else:
        return redirect(reverse('lab_9:login'))

def login(req):
    if req.user.is_authenticated:
        return redirect(reverse('lab_9:index'))
    if req.method == 'POST':
        username = req.POST['username']
        password = req.POST['password']
        user = authenticate(req, username=username, password=password)
        if user is not None:
            auth_login(req, user)
            return redirect('lab_9:index')
        else:
            form = AuthenticationForm()
            return render(req, 'lab_9/login.html', {'form': form, 'page_title': 'Login Page', 'error_msg': 'The E-mail and Password do not match'}, status=401)
    else:
        form = AuthenticationForm()
        return render(req, 'lab_9/login.html', {'form': form, 'page_title': 'Login Page', 'error_msg': ''})

def register(req):
    if req.user.is_authenticated:
        return redirect(reverse('lab_9:index'))
    if req.method == 'POST':
        form = UserCreationForm(req.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(req, username=username, password=password)
            auth_login(req, user)
            return redirect(reverse('lab_9:index'))
        else:
            return render(req, 'lab_9/register.html', {'form': form, 'page_title': 'Register Page'}, status=400)
    else:
        form = UserCreationForm()
        return render(req, 'lab_9/register.html', {'form': form, 'page_title': 'Register Page'})

def logout(req):
    auth_logout(req)
    return redirect(reverse('lab_9:login'))

lab_0/templates/lab_0/index.html
{% extends 'layouts/base.html' %} 

{% load static %}

{% block body %}

<section id="home" class="cover">
  <p class="lead">Kalem, idealis, suka begadang</p>
  <h1 class="cover-heading">
    Unique person, with all his question about the world
  </h1>
  <p class="lead mt-4">
    <a class="btn btn-lg btn-secondary" href="/#about">About Me</a>
  </p>
</section>

<section id="about" class="mb-5">
  <div class="jumbotron mb-5">
    <div class="container">
      <img
        src="{% static 'assets/fotoProfil.jpeg' %}"
        alt="foto-Profil"
        class="mx-auto col-md-6 mb-3 rounded-circle"
      />
      <h1 class="display-3">
        Hello, my name is <span class="highlight">Habib</span>ullah Akbar!
      </h1>
      <h3>but you can call me <span class="highlight">Habib</span></h3>
      <br />
      <p>
        🙌 I am a Software Engineer from Indonesia. Having expertise in coding
        websites 👨‍💻 and design graphics 🎨. Currently, I'm pursuing my
        undergrads 👨‍🎓 in Information System at<!-- -->
        <span class="highlight"
          >Faculty of Computer Science, University of Indonesia.</span
        >
      </p>
      <p>
        I am a person who is quick to learn things and able to work under
        pressure. I have a high level of interest and passion in the fields of<!-- -->
        <span class="highlight">science 👨‍🔬 and technology 🚀. </span>My life
        motto is "talk less 🤐, do more 💪".
      </p>
      <p></p>
      <a
        href="https://drive.google.com/file/d/1Ov1aT7n4csNRiDYy-ZApmYercbCJPZ1F/view?usp=sharing"
        rel="noreferrer"
        target="_blank"
        class="btn btn-secondary"
        >Get my Resume</a
      >
    </div>
  </div>

  <h2 class="mb-4">My Skills :</h2>

  <div class="container-bar"><div class="skills html">90%</div></div>
  <p class="text-left mb-4">HTML / CSS</p>
  <div class="container-bar"><div class="skills javascript">90%</div></div>
  <p class="text-left mb-4">Javascript / ReactJS / GatsbyJS / NextJS</p>
  <div class="container-bar"><div class="skills node">80%</div></div>
  <p class="text-left mb-4">NodeJS / Express</p>
  <div class="container-bar"><div class="skills python">80%</div></div>
  <p class="text-left mb-4">Python / Django</p>
  <div class="container-bar"><div class="skills database">80%</div></div>
  <p class="text-left mb-4">Database / PostgreSQL / MySQL / MongoDB</p>
  <div class="container-bar"><div class="skills java">80%</div></div>
  <p class="text-left mb-4">Java / Data Structure / Algorithm</p>
  <div class="container-bar"><div class="skills design">85%</div></div>
  <p class="text-left mb-4">Design Graphics</p>

  <h1 class="mb-4">My Timeline</h1>

  <div class="timeline">
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">Jan 2021 - Now</h2>
        <div class="btn badge mb-2">Work</div>
        <p>Work as a frontend developer intern at Pabryk</p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">Nov 2020 - Dec 2020</h2>
        <div class="btn badge mb-2">Work</div>
        <p>Work as a social media strategist intern at Skydu Academy</p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">March 2020 - May 2020</h2>
        <div class="btn badge mb-2">Volunteer</div>
        <p>Volunteer as staff of research study department, BEM UI 2020</p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">Feb 2019 - Dec 2019</h2>
        <div class="btn badge mb-2">Volunteer</div>
        <p>
          Volunteer as staff of propaganda and action department, BEM UI 2019
        </p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">July 2018</h2>
        <div class="btn badge mb-2">Edu</div>
        <p>
          Accepted as a student at the faculty of computer science, University
          of Indonesia
        </p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">May 2018</h2>
        <div class="btn badge mb-2">Edu</div>
        <p>
          Graduated from SMART Ekselensia Indonesia Senior High School in 2
          years, Acceleration Program
        </p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">April 2018</h2>
        <div class="btn badge mb-2">Achievment</div>
        <p>Got perfect score in senior high school mathematics national exam</p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">Oct 2017</h2>
        <div class="btn badge mb-2">Award</div>
        <p>UIN Jakarta Physics Olympiad, 1st Place</p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">March 2017</h2>
        <div class="btn badge mb-2">Award</div>
        <p>OSN Computer, 1st place at Bogor Regency level</p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">June 2016</h2>
        <div class="btn badge mb-2">Edu</div>
        <p>Graduated from SMART Ekselensia Indonesia Junior High School</p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">May 2016</h2>
        <div class="btn badge mb-2">Achievment</div>
        <p>Got perfect score in junior high school mathematics national exam</p>
      </div>
    </div>
    <div class="container-timeline">
      <div class="content">
        <h2 class="highlight">May 2013</h2>
        <div class="btn badge mb-2">Achievment</div>
        <p>Got perfect score in elementary school mathematics national exam</p>
      </div>
    </div>
  </div>
</section>

<section id="projects">
  <h2>My Several Projects:</h2>
  <div class="row justify-content-center">
    <div class="card p-0 m-2 w-100">
      <div class="row no-gutters">
        <div class="col-md-8">
          <img src="{% static 'assets/pdharapanjaya.png' %}" class="card-img" />
        </div>
        <div class="col-md-4">
          <div class="card-body">
            <h5 class="card-title">PD Harapan Jaya</h5>
            <p class="card-text">
              This is simple landing page for PD Harapan Jaya.
            </p>
            <a
              href="https://pdharapanjayatangerang.com/"
              class="btn btn-secondary"
              rel="noreferrer"
              target="_blank"
              >Visit</a
            >
          </div>
        </div>
      </div>
    </div>
    <div class="card p-0 m-2 w-100">
      <div class="row no-gutters">
        <div class="col-md-8">
          <img src="{% static 'assets/chavyvblog.png' %}" class="card-img" />
        </div>
        <div class="col-md-4">
          <div class="card-body">
            <h5 class="card-title">Chavyv Blog</h5>
            <p class="card-text">
              This is my blog for share something about my life or random
              thoughts.
            </p>
            <a
              href="https://blog.chavyv.xyz/"
              class="btn btn-secondary"
              rel="noreferrer"
              target="_blank"
              >Visit</a
            >
          </div>
        </div>
      </div>
    </div>
    <div class="card p-0 m-2 w-100">
      <div class="row no-gutters">
        <div class="col-md-8">
          <img src="{% static 'assets/memorygame.png' %}" class="card-img" />
        </div>
        <div class="col-md-4">
          <div class="card-body">
            <h5 class="card-title">Memory Game</h5>
            <p class="card-text">
              This is a simple memory game built with React.
            </p>
            <a
              href="https://kind-haibt-e00960.netlify.app/"
              class="btn btn-secondary"
              rel="noreferrer"
              target="_blank"
              >Visit</a
            >
          </div>
        </div>
      </div>
    </div>
    <div class="card p-0 m-2 w-100">
      <div class="row no-gutters">
        <div class="col-md-8">
          <img src="{% static 'assets/hejokeun.png' %}" class="card-img" />
        </div>
        <div class="col-md-4">
          <div class="card-body">
            <h5 class="card-title">Hejokeun.id</h5>
            <p class="card-text">
              This is an educational blog for environmental issues.
            </p>
            <a
              href="https://fleadsasean.firebaseapp.com/"
              class="btn btn-secondary"
              rel="noreferrer"
              target="_blank"
              >Visit</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="contacts" class="mt-5">
  <h2>You can reach me with:</h2>
  <div class="contact-icon">
    <a href="mailto:akbar2habibulah@gmail.com" rel="noreferrer" target="_blank"
      ><i class="far fa-envelope fa-3x"></i></a
    ><a
      href="https://instagram.com/chavyv.akvar"
      rel="noreferrer"
      target="_blank"
      ><i class="fab fa-instagram fa-3x"></i></a
    ><a href="https://twitter.com/ChavyvAkvar" rel="noreferrer" target="_blank"
      ><i class="fab fa-twitter fa-3x"></i></a
    ><a
      href="https://www.linkedin.com/in/habibullah-akbar-631880179/"
      rel="noreferrer"
      target="_blank"
      ><i class="fab fa-linkedin-in fa-3x"></i></a
    ><a
      href="https://github.com/akbar2habibullah"
      rel="noreferrer"
      target="_blank"
      ><i class="fab fa-github fa-3x"></i></a
    ><a
      href="https://gitlab.com/akbar2habibullah"
      rel="noreferrer"
      target="_blank"
      ><i class="fab fa-gitlab fa-3x"></i
    ></a>
  </div>
</section>

{% endblock body %}

lab_0/templates/lab_0/ppw.html
{% extends 'layouts/base.html' %}

{% block body %}

<div class="row mt-5">
    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="{% url 'lab_1:index' %}">Story 1</a></h3>
            </div>
            <div class="card-body">
                Tugas story 1
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="{% url 'lab_2:index' %}">Story 2</a></h3>
            </div>
            <div class="card-body">
                Tugas story 2
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="{% url 'lab_3:index' %}">Story 3</a></h3>
            </div>
            <div class="card-body">
                Tugas story 3
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="{% url 'lab_4:index' %}">Story 4</a></h3>
            </div>
            <div class="card-body">
                Tugas story 4
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="{% url 'lab_5:index' %}">Story 5</a></h3>
            </div>
            <div class="card-body">
                Tugas story 5
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="#">Story 6</a></h3>
            </div>
            <div class="card-body">
                Lorem ipsum dolor sit amet
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="{% url 'lab_7:index' %}">Story 7</a></h3>
            </div>
            <div class="card-body">
                Tugas story 7
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="{% url 'lab_8:index' %}">Story 8</a></h3>
            </div>
            <div class="card-body">
                Tugas story 8
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 col-lg-4 my-2">
        <div class="card p-2">
            <div class="card-title">
                <h3><a href="{% url 'lab_9:index' %}">Story 9</a></h3>
            </div>
            <div class="card-body">
                Tugas story 9
            </div>
        </div>
    </div>
</div>

{% endblock body %}

lab_1/templates/lab_1/index.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block body %}

<div class="card card-body text-left mx-auto my-5" style="width: 18rem;">
    <img src="{% static 'assets/fotoProfil.jpeg' %}" alt="foto profil" class="rounded-circle col-8 mx-auto mb-3">
    <h3>Nama:</h3>
    <p>Habibullah Akbar</p>
    <h3>NPM:</h3>
    <p>1806191351</p>
    <h3>Angkatan:</h3>
    <p>2018</p>
    <h3>Hobi:</h3>
    <p>Rebahan</p>
    <h3>Deskripsi:</h3>
    <p>Kalem, idealis, suka begadang</p>
    <h3>Tempat Kuliah:</h3>
    <p>Pacil</p>
    <h3>Pendidikan:</h3>
    <p>S1 on-going</p>
    <h3>Medsos:</h3>
    <p>@chavyv.akvar</p>
</div>

{% endblock %}